Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-PadInstallRoot {
    if ($env:PAD_INSTALL_ROOT) {
        return [IO.Path]::GetFullPath($env:PAD_INSTALL_ROOT)
    }
    return [IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.."))
}

function Get-PadPaths {
    $root = Get-PadInstallRoot
    [pscustomobject]@{
        Root = $root
        Config = Join-Path $root "config"
        RuntimeEnv = Join-Path $root "config\runtime.env"
        DefaultsEnv = Join-Path $root "config\defaults.env"
        Runtime = Join-Path $root "config\runtime"
        State = Join-Path $root "state"
        Logs = Join-Path $root "logs"
        Session = Join-Path $root "state\attached-session.json"
        Bootstrap = Join-Path $root "state\bootstrap.json"
        Compose = Join-Path $root "docker-compose.yml"
    }
}

function Write-PadMessage {
    param([Parameter(Mandatory)][string]$Message)
    Write-Host "[pad] $Message"
}

function Read-PadEnvFile {
    param([Parameter(Mandatory)][string]$Path)
    $values = [ordered]@{}
    if (-not (Test-Path -LiteralPath $Path)) { return $values }
    foreach ($line in [IO.File]::ReadAllLines($Path)) {
        if ([string]::IsNullOrWhiteSpace($line) -or $line.TrimStart().StartsWith("#")) { continue }
        $index = $line.IndexOf("=")
        if ($index -lt 1) { continue }
        $values[$line.Substring(0, $index).Trim()] = $line.Substring($index + 1)
    }
    return $values
}

function Get-PadEnvironment {
    $paths = Get-PadPaths
    $values = [ordered]@{}
    foreach ($path in @($paths.DefaultsEnv, $paths.RuntimeEnv)) {
        $fileValues = Read-PadEnvFile -Path $path
        foreach ($entry in $fileValues.GetEnumerator()) { $values[$entry.Key] = $entry.Value }
    }
    $overrides = @{
        PAD_APP_PORT = "APP_PORT"
        PAD_CODER_PORT = "CODER_PORT"
        PAD_KEYCLOAK_PORT = "KEYCLOAK_PORT"
    }
    foreach ($item in $overrides.GetEnumerator()) {
        $override = [Environment]::GetEnvironmentVariable($item.Key, "Process")
        if ($override) { $values[$item.Value] = $override }
    }
    return $values
}

function Set-PadEnvValue {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Name,
        [AllowEmptyString()][string]$Value
    )
    $lines = [Collections.Generic.List[string]]::new()
    if (Test-Path -LiteralPath $Path) {
        $lines.AddRange([string[]][IO.File]::ReadAllLines($Path))
    }
    $updated = $false
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index] -match "^$([regex]::Escape($Name))=") {
            $lines[$index] = "$Name=$Value"
            $updated = $true
            break
        }
    }
    if (-not $updated) { $lines.Add("$Name=$Value") }
    $encoding = [Text.UTF8Encoding]::new($false)
    [IO.File]::WriteAllLines($Path, $lines, $encoding)
}

function New-PadSecret {
    param([ValidateRange(16, 256)][int]$Bytes = 32)
    $buffer = [byte[]]::new($Bytes)
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try { $generator.GetBytes($buffer) } finally { $generator.Dispose() }
    return [Convert]::ToBase64String($buffer).TrimEnd("=").Replace("+", "-").Replace("/", "_")
}

function Protect-PadConfiguration {
    param([Parameter(Mandatory)][string]$Path)
    if ($env:OS -ne "Windows_NT" -or -not (Test-Path -LiteralPath $Path)) { return }
    try {
        & icacls.exe $Path /inheritance:r /grant:r "$($env:USERNAME):(F)" | Out-Null
    } catch {
        Write-Warning "Could not restrict the ACL on $Path. $($_.Exception.Message)"
    }
}

function Initialize-PadConfiguration {
    $paths = Get-PadPaths
    foreach ($directory in @($paths.Config, $paths.Runtime, $paths.State, $paths.Logs)) {
        [IO.Directory]::CreateDirectory($directory) | Out-Null
    }
    if (-not (Test-Path -LiteralPath $paths.DefaultsEnv)) {
        throw "Missing configuration defaults at $($paths.DefaultsEnv). Reinstall Pad Local."
    }
    if (-not (Test-Path -LiteralPath $paths.RuntimeEnv)) {
        [IO.File]::WriteAllText($paths.RuntimeEnv, "# Generated by Pad Local. Do not commit this file.`n", [Text.UTF8Encoding]::new($false))
    }

    $requiredSecrets = @(
        "POSTGRES_PASSWORD", "REDIS_PASSWORD", "KEYCLOAK_ADMIN_PASSWORD",
        "OIDC_CLIENT_SECRET", "PAD_SESSION_SECRET", "PAD_BOOTSTRAP_PASSWORD",
        "CODER_BOOTSTRAP_PASSWORD"
    )
    $environment = Get-PadEnvironment
    foreach ($name in $requiredSecrets) {
        if (-not $environment.Contains($name) -or [string]::IsNullOrWhiteSpace($environment[$name])) {
            Set-PadEnvValue -Path $paths.RuntimeEnv -Name $name -Value (New-PadSecret)
        }
    }
    foreach ($entry in @{
        CODER_API_KEY = ""
        CODER_TEMPLATE_ID = ""
        CODER_DEFAULT_ORGANIZATION = ""
        CODER_BOOTSTRAP_EMAIL = "coder-admin@localhost"
        CODER_BOOTSTRAP_USER = "pad-admin"
    }.GetEnumerator()) {
        $environment = Get-PadEnvironment
        if (-not $environment.Contains($entry.Key)) {
            Set-PadEnvValue -Path $paths.RuntimeEnv -Name $entry.Key -Value $entry.Value
        }
    }

    $environment = Get-PadEnvironment
    $templatePath = Join-Path $paths.Config "keycloak\realm-template.json"
    if (-not (Test-Path -LiteralPath $templatePath)) { throw "Missing Keycloak realm template: $templatePath" }
    $realm = [IO.File]::ReadAllText($templatePath)
    foreach ($name in @(
        "OIDC_REALM", "OIDC_CLIENT_ID", "OIDC_CLIENT_SECRET", "APP_PORT", "CODER_PORT",
        "PAD_BOOTSTRAP_USER", "PAD_BOOTSTRAP_EMAIL", "PAD_BOOTSTRAP_PASSWORD"
    )) {
        if (-not $environment.Contains($name)) { throw "Required configuration value $name is missing." }
        $realm = $realm.Replace("__$name`__", [string]$environment[$name])
    }
    $realmPath = Join-Path $paths.Runtime "keycloak-realm.json"
    [IO.File]::WriteAllText($realmPath, $realm, [Text.UTF8Encoding]::new($false))
    Protect-PadConfiguration -Path $paths.RuntimeEnv
    Protect-PadConfiguration -Path $realmPath
    return $environment
}

function Find-DockerDesktop {
    $candidates = @(
        (Join-Path $env:ProgramFiles "Docker\Docker\Docker Desktop.exe"),
        (Join-Path $env:LOCALAPPDATA "Programs\DockerDesktop\Docker Desktop.exe"),
        (Join-Path $env:LOCALAPPDATA "Docker\Docker Desktop.exe")
    )
    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }
    return $null
}

function Add-DockerCliToCurrentPath {
    if (Get-Command docker -ErrorAction SilentlyContinue) { return }
    $cliDirectories = @(
        (Join-Path $env:ProgramFiles "Docker\Docker\resources\bin"),
        (Join-Path $env:LOCALAPPDATA "Programs\DockerDesktop\resources\bin")
    )
    foreach ($cliDirectory in $cliDirectories) {
        if (Test-Path -LiteralPath (Join-Path $cliDirectory "docker.exe")) {
            $env:Path = "$cliDirectory;$($env:Path)"
            return
        }
    }
}

function Invoke-DockerProbe {
    param([Parameter(Mandatory)][string[]]$Arguments)
    $previousErrorActionPreference = $ErrorActionPreference
    try {
        # Windows PowerShell 5.1 promotes redirected native stderr to an
        # ErrorRecord. Suppress it while probing so the exit code can be
        # handled below instead of terminating under ErrorActionPreference=Stop.
        $ErrorActionPreference = "SilentlyContinue"
        $output = @(& docker @Arguments 2>$null)
        $exitCode = $LASTEXITCODE
    } catch {
        $output = @()
        $exitCode = 1
    } finally {
        $ErrorActionPreference = $previousErrorActionPreference
    }
    [pscustomobject]@{
        ExitCode = $exitCode
        Output = ($output -join "`n").Trim()
    }
}

function Wait-DockerDaemon {
    param([ValidateRange(10, 600)][int]$TimeoutSeconds = 180)
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        $probe = Invoke-DockerProbe -Arguments @("info", "--format", "{{.OSType}}")
        if ($probe.ExitCode -eq 0) { return }
        Start-Sleep -Seconds 3
    } while ([DateTime]::UtcNow -lt $deadline)
    throw "Docker Desktop did not become ready within $TimeoutSeconds seconds. Open Docker Desktop and retry."
}

function Assert-PadDocker {
    param([switch]$StartIfNeeded)
    Add-DockerCliToCurrentPath
    $dockerDesktop = if ($env:OS -eq "Windows_NT") { Find-DockerDesktop } else { $null }
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        if ($env:OS -eq "Windows_NT" -and -not $dockerDesktop) {
            throw "Docker Desktop is not installed. Install Docker Desktop with WSL2 and enable Linux containers, then retry."
        }
        throw "The Docker CLI is not available on PATH. Install Docker Desktop (Windows) or Docker Engine (Linux)."
    }
    $probe = Invoke-DockerProbe -Arguments @("info", "--format", "{{.OSType}}")
    if ($probe.ExitCode -ne 0) {
        if ($StartIfNeeded -and $dockerDesktop) {
            Write-PadMessage "Starting Docker Desktop..."
            Start-Process -FilePath $dockerDesktop | Out-Null
            Wait-DockerDaemon
        } else {
            throw "The Docker daemon is not reachable. Start Docker Desktop and retry."
        }
    }
    $probe = Invoke-DockerProbe -Arguments @("info", "--format", "{{.OSType}}")
    if ($probe.ExitCode -ne 0 -or $probe.Output -ne "linux") {
        throw "Docker Desktop must use Linux containers. Switch to the Linux container engine and retry."
    }
    $probe = Invoke-DockerProbe -Arguments @("compose", "version")
    if ($probe.ExitCode -ne 0) { throw "Docker Compose v2 is required. Update Docker Desktop and verify 'docker compose version'." }
}

function Get-PadComposeArguments {
    $paths = Get-PadPaths
    foreach ($mapping in @{
        PAD_APP_PORT = "APP_PORT"
        PAD_CODER_PORT = "CODER_PORT"
        PAD_KEYCLOAK_PORT = "KEYCLOAK_PORT"
    }.GetEnumerator()) {
        $value = [Environment]::GetEnvironmentVariable($mapping.Key, "Process")
        if ($value) { [Environment]::SetEnvironmentVariable($mapping.Value, $value, "Process") }
    }
    return @(
        "compose", "--project-name", "pad-local",
        "--env-file", $paths.DefaultsEnv,
        "--env-file", $paths.RuntimeEnv,
        "--file", $paths.Compose
    )
}

function Invoke-PadCompose {
    param(
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments,
        [switch]$AllowFailure
    )
    $paths = Get-PadPaths
    Push-Location $paths.Root
    try {
        $composeArguments = @(Get-PadComposeArguments) + $Arguments
        & docker @composeArguments
        $exitCode = $LASTEXITCODE
        if ($exitCode -ne 0 -and -not $AllowFailure) {
            throw "Docker Compose failed with exit code $exitCode."
        }
        return $exitCode
    } finally {
        Pop-Location
    }
}

function Invoke-PadComposeCapture {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)
    $paths = Get-PadPaths
    Push-Location $paths.Root
    try {
        $composeArguments = @(Get-PadComposeArguments) + $Arguments
        $output = & docker @composeArguments 2>&1
        if ($LASTEXITCODE -ne 0) { throw ($output -join [Environment]::NewLine) }
        return $output
    } finally { Pop-Location }
}

function Wait-PadUrl {
    param(
        [Parameter(Mandatory)][string]$Url,
        [ValidateRange(5, 900)][int]$TimeoutSeconds = 300,
        [hashtable]$Headers = @{}
    )
    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    do {
        try {
            $response = Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 5 -Headers $Headers
            if ($response.StatusCode -ge 200 -and $response.StatusCode -lt 500) { return $response }
        } catch { }
        Start-Sleep -Seconds 3
    } while ([DateTime]::UtcNow -lt $deadline)
    throw "Timed out waiting for $Url"
}

function Test-PadStackRunning {
    try {
        $services = @(Invoke-PadComposeCapture ps --services --filter "status=running")
        return $services.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace(($services -join ""))
    } catch { return $false }
}

function Test-PadPortAvailable {
    param([Parameter(Mandatory)][int]$Port)
    if (Get-Command Get-NetTCPConnection -ErrorAction SilentlyContinue) {
        $connection = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($connection) {
            $process = Get-Process -Id $connection.OwningProcess -ErrorAction SilentlyContinue
            $description = if ($process) { "$($process.ProcessName) (PID $($process.Id))" } else { "PID $($connection.OwningProcess)" }
            return [pscustomobject]@{ Available = $false; Owner = $description }
        }
    } else {
        $listener = [Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback, $Port)
        try { $listener.Start(); return [pscustomobject]@{ Available = $true; Owner = "" } }
        catch { return [pscustomobject]@{ Available = $false; Owner = "another process" } }
        finally { try { $listener.Stop() } catch { } }
    }
    return [pscustomobject]@{ Available = $true; Owner = "" }
}

function Assert-PadPorts {
    if (Test-PadStackRunning) { return }
    $environment = Get-PadEnvironment
    foreach ($name in @("APP_PORT", "CODER_PORT", "KEYCLOAK_PORT")) {
        $result = Test-PadPortAvailable -Port ([int]$environment[$name])
        if (-not $result.Available) {
            throw "Port $($environment[$name]) ($name) is already used by $($result.Owner). Stop that process or run 'pad config set $($name.ToLower().Replace('_port','.port')) <port>'."
        }
    }
}

function Test-CoderApiToken {
    param([string]$Token)
    if ([string]::IsNullOrWhiteSpace($Token)) { return $false }
    $environment = Get-PadEnvironment
    try {
        $headers = @{ "Coder-Session-Token" = $Token }
        $response = Invoke-WebRequest -Uri "http://localhost:$($environment.CODER_PORT)/api/v2/users/me" -UseBasicParsing -TimeoutSec 8 -Headers $headers
        return $response.StatusCode -eq 200
    } catch { return $false }
}

function Invoke-CoderCli {
    param(
        [string]$SessionToken,
        [Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments
    )
    $prefix = @("exec", "-T")
    if ($SessionToken) { $prefix += @("-e", "CODER_SESSION_TOKEN=$SessionToken") }
    $prefix += @("coder", "/opt/coder")
    return @(Invoke-PadComposeCapture @prefix @Arguments)
}

function Initialize-CoderBootstrap {
    $paths = Get-PadPaths
    $environment = Get-PadEnvironment
    if (Test-CoderApiToken -Token ([string]$environment.CODER_API_KEY)) {
        return
    }
    Write-PadMessage "Bootstrapping Coder administrator, organization, token, and template..."
    $url = "http://127.0.0.1:7080"
    $sessionToken = ""
    try {
        $sessionToken = ((Invoke-CoderCli -SessionToken "" login token) -join "`n").Trim()
    } catch { }
    if (-not $sessionToken) {
        $loginArguments = @(
            "login", $url,
            "--first-user-email", [string]$environment.CODER_BOOTSTRAP_EMAIL,
            "--first-user-username", [string]$environment.CODER_BOOTSTRAP_USER,
            "--first-user-full-name", "Pad Local Administrator",
            "--first-user-password", [string]$environment.CODER_BOOTSTRAP_PASSWORD,
            "--first-user-trial=false"
        )
        Invoke-CoderCli -SessionToken "" @loginArguments | Out-Null
        $sessionToken = ((Invoke-CoderCli -SessionToken "" login token) -join "`n").Trim()
    }
    if (-not $sessionToken) { throw "Coder did not return a bootstrap session token." }

    $apiToken = ((Invoke-CoderCli -SessionToken $sessionToken tokens create --name pad-local-backend --lifetime 10y) -join "`n").Trim()
    if (-not $apiToken) { throw "Coder automation token creation returned no token." }
    $organizationId = ((Invoke-CoderCli -SessionToken $sessionToken organizations show selected --only-id) -join "`n").Trim()
    if (-not $organizationId) { throw "Coder default organization discovery returned no ID." }

    $pushArguments = @(
        "templates", "push", [string]$environment.CODER_TEMPLATE_NAME,
        "--directory", "/opt/pad/coder-template", "--yes"
    )
    Invoke-CoderCli -SessionToken $sessionToken @pushArguments | Out-Null
    $templatesJson = (Invoke-CoderCli -SessionToken $sessionToken templates list --output json) -join "`n"
    $templates = $templatesJson | ConvertFrom-Json
    $template = @($templates) | Where-Object { $_.name -eq $environment.CODER_TEMPLATE_NAME } | Select-Object -First 1
    if (-not $template -or -not $template.id) { throw "Coder template ID discovery failed." }

    Set-PadEnvValue -Path $paths.RuntimeEnv -Name "CODER_API_KEY" -Value $apiToken
    Set-PadEnvValue -Path $paths.RuntimeEnv -Name "CODER_DEFAULT_ORGANIZATION" -Value $organizationId
    Set-PadEnvValue -Path $paths.RuntimeEnv -Name "CODER_TEMPLATE_ID" -Value ([string]$template.id)
    Protect-PadConfiguration -Path $paths.RuntimeEnv
    [IO.File]::WriteAllText(
        $paths.Bootstrap,
        ([ordered]@{ complete = $true; completedAt = [DateTime]::UtcNow.ToString("o"); templateId = [string]$template.id; organizationId = $organizationId } | ConvertTo-Json),
        [Text.UTF8Encoding]::new($false)
    )
}

function Start-PadServices {
    param([switch]$Build)
    Assert-PadDocker -StartIfNeeded
    Initialize-PadConfiguration | Out-Null
    Assert-PadPorts
    Write-PadMessage "Starting databases, Keycloak, and Coder..."
    Invoke-PadCompose up --detach postgres redis docker-proxy keycloak coder | Out-Null
    $environment = Get-PadEnvironment
    Wait-PadUrl -Url "http://localhost:$($environment.KEYCLOAK_PORT)/realms/$($environment.OIDC_REALM)/.well-known/openid-configuration" -TimeoutSeconds 360 | Out-Null
    Wait-PadUrl -Url "http://localhost:$($environment.CODER_PORT)/api/v2/buildinfo" -TimeoutSeconds 360 | Out-Null
    Initialize-CoderBootstrap
    Write-PadMessage "Starting Pad website..."
    $arguments = @("up", "-d")
    if ($Build) { $arguments += "--build" }
    $arguments += @("app", "frontend")
    Invoke-PadCompose @arguments | Out-Null
    $environment = Get-PadEnvironment
    Wait-PadUrl -Url "http://localhost:$($environment.APP_PORT)/api/app/health" -TimeoutSeconds 360 | Out-Null
}

function Stop-PadServices {
    Assert-PadDocker
    Invoke-PadCompose stop | Out-Null
}

function Open-PadBrowser {
    $environment = Get-PadEnvironment
    $url = "http://localhost:$($environment.APP_PORT)"
    if ($env:PAD_NO_BROWSER -eq "1") { return $url }
    try { Start-Process $url | Out-Null } catch { Write-Warning "Could not open the browser. Open $url manually." }
    return $url
}
